runtime: nodejs10
service: snesbot
manual_scaling:
        instances: 1
env_variables:
        PUBSUB_TOPIC: "reminders"
        PORT: 8080
        PROJECT_ID: "popbot-discord"
        CLOUD_BUCKET: "snesbot-overflow"
